### ISSUE TITLE
Animations not working Figura 0.1.3 pre.4+1.20.1

### ISSUE THREAD

**Issue by KalinTDM-Playz** [GrandpaScout/GSAnimBlend#2] opened 2024-02-11 04:00 UTC
![2024-02-10_21 47 05](https://github.com/GrandpaScout/GSAnimBlend/assets/58379398/97ad572b-d231-40d4-8fdb-40bfca041dee)
I was wondering If you could make an update for GSAnimBlend, cause the current version isn't working

**Comment by GrandpaScout** [comment] 2024-02-11 06:32
This is an issue with Figura Forge caused by the `client.getFiguraVersion()` function only getting the prerelease info from Figura instead of the full thing.
I'll put out a workaround eventually.

**Comment by GrandpaScout** [comment] 2024-02-11 06:56
It seems like your version of GSAnimBlend is also *not* up-to-date.

Once you update it, you can fix this issue for now by changing https://github.com/GrandpaScout/GSAnimBlend/blob/46c07a6da56090cc099fb01e41eebcc76c757b67/script/GSAnimBlend.lua#L1994 to
```lua
local cmp, ver = client.compareVersions, client.getFiguraVersion():match("^([^%+]*)"):gsub("^([pr].*)$", "0.1.3-%1")
```

**Comment by GrandpaScout** [comment] 2024-02-11 07:15
***Nevermind***. This issue is completely unrelated to GSAnimBlend. It isn't even my script erroring.
Please refer to the original author of the avatar template you are using.

The fix for GSAnimBlend itself still stands however and will be fixed soon.

**Closed as not planned by GrandpaScout** 2024-02-11 07:15 UTC
